---
geometry: "left=1cm,right=1cm,top=2.5cm,bottom=2.5cm"
output:
  bookdown::pdf_document2:
    latex_engine: lualatex
    toc: false
header-includes:
- \usepackage{caption}
fontsize: 11pt
mainfont: Arial
linestretch: 1.5
bibliography: reference.bib
csl: vancouver-superscript.csl
keep_tex: yes
---

#	Introduction (400-500)
In the clinical trial, Individual patient (participant) data has been well acknowledged by different stakeholders as the most informative one to conduct quantitative research (xxx) though aggregate-level data was the most common evidence published in the journal. Especially with the prevalence of meta-analysis in various disciplines, IPD meta-analysis has become the gold standard methodology in the evidence synthesis of evidence-based medicine. However, the limited availability of IPD rendered researchers unable to acquire adequate IPD in the open access database. Thus, a range of published methods intended to combine IPD and aggregate-level data into the meta-analysis to address the lack of evidence. Especially, recently one of methodology multilevel network meta-analysis (ML-NMA) was proposed by Phillippo et al. to extend the standard network meta-analysis (NMA) and was applied in this study. 

However, except the common aggregate-level data, subgroup results are also frequently published to show the heterogeneity of treatment effect regarding to various stratification including baseline characteristics, genetic information and etc. Although pitfalls of subgroup results have been criticized substantially by a number of published papers as low power, risk of overfitting and increased false-positive error (xxx), in principle, a potentially useful information could still be acquired in the subgroup analyses under well-planned and executed study design. (xxx)

Given the subgroup effects, there is one issue that multiple subgroup effects presented are not independent and cannot be included in a single analysis under aforementioned framework. However, single subgroup effect could be incorporated into current ML-NMA framework using existing software R language. Therefore, in this study, we conduct a simulation study in a tutorial manner to demonstrate how to include the post-hoc subgroup effects in the network meta-analysis, also presenting the additional benefits of subgroup effects in the evidence synthesis.

#	Methods (700-800)
The multilevel network meta-regression (ML-NMR) proposed by Phillippo was extended in this simulation study to incorporate the subgroup results in the network meta-analysis. We aimed to assess whether the integration of single subgroup results with IPD and aggregate data in the network meta-analysis could calibrate the treatment effect and provide a more precise estimation of treatment-covariate interaction effect and relative treatment effect.

## Data collection
The data released in the R package Multinma was applied in this study, which contained 4 IPD studies IXORA-S, UNCOVER-1, UNCOVER-2, and UNCOVER-3(xxx). All of them were extracted from IPD of phase III clinical trial targeting to the plaque psoriasis. 

Regarding to the outcome variables, PASI is the common endpoint in the clinical trial to measure the severity of psoriasis(xxx). In this study, we selected PASI 75 as outcome which mean means if the percentage of change of PASI from baseline is greater than 75%, then PASI 75 was coded as 1 otherwise 0. Based on the vignette of MULTINMA package, multiple covariates were selected, including duration of psoriasis (DoR), previous systematic disease (TRUE/FALSE), body surface area (BSA), weight, and psoriatic arthritis status (TRUE/FALSE).

### Scenario
Based on the original data, we will also generate subgroup results and aggregate data from one of the IPD. Thus, three scenarios of data were designed in this study. Base scenario was all IPD; second scenario was three IPD and one subgroup result modified from one IPD; third scenario was three IPD and one aggregate data modified from one IPD.

To create the data under three scenarios, age and duration of psoriasis (DoR) were considered as two stratified factors to generate post-hoc subgroup results and aggregate data. Also, regarding to the the maximal availability of data, the subgroup results were generated by the IPD from UNCOVER-3. Generally, aggregate data is the summary information of treatment-level by studies and subgroup results is the summary information based on treament and subgroup effect of each study. 

2.3	Analysis
2.3.1 Models
After generating subgroup result and aggregate data from IPD of study UNCOVER-3, three ML-NMR were generated for subgroup effect of age and DoR respectively. The generation of ML-NMR was implemented in R programming language. Specifically, there are two key steps in the implementation of ML-NMR. First, we defined a IPD model with prespecified covariates in section 2.1. Second, the aggregate data could be combined with IPD model as an integration of the IPD model over the covariate distributions in each trial. To maintain comparability with earlier analyses, a probit link was utilised (xxx). The individual level and aggregate level model notation(xxx) were shown as follows.
\
**Individual level model:**  
\begin{align*}
y_{ijk} \sim& \pi_{Ind}(\theta_{ijk}),\\
g(\theta_{ijk}) =& \eta_{jk}(x_{ijk})) = \mu_j + x_{ijk}^T\beta + \gamma_k;
\end{align*}
\
**Aggregate level model:**  
\begin{align*}
y_{.jk} \sim& \pi_{Agg}(\theta_{.jk}),\\
\theta_{\cdot jk} =& \int_{\mathfrak{X}} g^{-1}\{\eta_{jk}(x)\}f_{jk}(x)dx;
\end{align*}

The configurations of models above were as specified(xxx):  
\
**Individual level model:**  
1. $y_{ijk}$ and $X_{ijk}$ are the responses and covariates of patients i for treatment k in study j;  
2. $\pi_{Ind}$ is the likelihood distribution of individual level model; $\theta_{\cdot jk}$ is the conditional average outcome of patients I of treatment k in study j;  
3. g(*) is the link function of individual model;  
4. $\eta_{jk}(x_{ijk})$ is the linear predictor of $X_{ijk}$; $\mu_j$ is the baseline results of study j; $x_{ijk}^T$ is algebra expression to represent the transposed $X_{ijk}$, $\beta$ are the coefficients matrix of covariates;  
5. $\gamma_k$ is the effect of treatment k compared to the referenced treatment.    
\
**Aggregate level model:**  
1. $\pi_{Agg}$ is the likelihood distribution of individual level model; $\theta_{\cdot jk}$ is the marginal average outcome of treatment k in study j;   
2. $y_{.jk}$ is the outcome of aggregate model;  
3. $\mathfrak{X}$ is the support of X; $f_{jk}(x)$ is the function of covariates of treatment k in study j;  
4. $g^{-1}\{\eta_{jk}(x)\}$ is the inverse function of linear predictor.  
\
The individual level model could be explicitly regarded as a generalized linear model based on IPD. Whereas the aggregate level model was derived in an intuitive way. Based on the probability theory, the marginal probability of $X$ is calculated by assessing the conditional likelihood of $X$ given a specific value of $Y$ and then averaging this conditional probability over the whole distribution of Y. The equation is as follows:  
\begin{align*}
p_X(x) = \int_{x}p_{X|Y}(x|y)p_{Y}(y)dy
\end{align*}
\

2.3.2 Subgroup result compared with aggregate data
The structure of subgroup result is similar to the aggregare data. 


2.3.3 Code comparison with standard analysis


```{r, warning=FALSE, message=FALSE, error=FALSE, include=FALSE}
sub_eff_func <- function(group_vars, name_) {
  
  sub_ipd %>% 
    group_by(!!!group_vars) %>%
    summarise(age_mean = mean(age),
              age_sd = sd(age),
              bmi_mean = mean(bmi, na.rm = TRUE),
              bmi_sd = sd(bmi, na.rm = TRUE),
              weight_mean = mean(bmi, na.rm = TRUE),
              weight_sd = sd(bmi, na.rm = TRUE),
              durnpso_mean = mean(durnpso),
              durnpso_sd = sd(durnpso),
              pasi75_n = n(),
              pasi75_r = sum(pasi75),
              pasi90_n = n(),
              pasi90_r = sum(pasi90),
              pasi100_n = n(),
              pasi100_r = sum(pasi100), 
              psa = mean(psa), 
              prevsys = mean(prevsys), 
              male = mean(male),
              bsa_mean = mean(bsa), 
              bsa_sd = sd(bsa)) %>%
    mutate(studyc = paste(studyc, name_)) 
  
}

## convert IPD to aggregate data
ipd_agd <- sub_eff_func(quos(studyc, trtc, trtclass, trtn, trtc_long), "IPD")

## convert IPD to duration-specific subgroup IPD
agd_sub_durn <- sub_eff_func(quos(studyc, trtc, trtclass, trtn, trtc_long, sub_durn), "SUB")

## convert IPD to age-specific subgroup IPD
agd_sub_durn <- sub_eff_func(quos(studyc, trtc, trtclass, trtn, trtc_long, sub_age), "SUB")

## combine original aggregate data with derived aggregate data and subgroup results
sub_agd1 <- bind_rows(sub_agd,
                      agd_sub_durn,
                      agd_sub_age,
                      ipd_agd)

```

#	Results (700-800)

## Findings for interactions

Figure xxx showed the estimations of treatment-covariate interactions in three scenarios. Unequivocally, the estimation of interaction in the base scenario (e.g. age-TNFa block estimation: -0.269 (95%CI: -0.418, -0.12)) was the most precise compared with other two scnearios, followed by the subgroup scenario (e.g. age-TNFa block estimation: -0.388 (95%CI: -0.58, -0.212)) and then aggregare scenario (e.g. age-TNFa block estimation: -0.425 (95%CI: -0.696, -0.162)). This result also echoed the argument that IPD meta-analysis is the gold standatd of evidence synthesis (xxx). Notably, it is evident that differences of estimations existed between these three scenarios, which were reflected in the narrower interval of coefficients of covariates, covariate-treatment interactions in the subgroup set compared to the aggregate set. Furthermore, the estimations in the subgroup scenario were much closer to the base case than aggregate scenario.

To confirm the consistency of result generated by this extended approach, we conducted same simulation choosing DoR as subgroup effect. The forest plot of treatment-covariate interactions was shown in Figure xx. Generally, the results are similar to the simulation with age. The precision of estimation in the base scenario is the most accurate. Compared with the aggregate scenario, the estimation in the subgroup scenario was more precise and closer to the estimations in the base scenario.

## Comparison of population-adjusted relative treatment effect
Regarding to the population-adjusted relative treatment effect compared to the placebo treatment, Figure xxx illustrated these based on the subject characteristics of UNCOVER-3 study. On the one hand, compared to the results of covariate-treatment interaction, the differences of estimations from three scenarios were relatively less differential though the estimations from base case was always the most accurate and stable. On another hand, the precision of estimations from subgroup scenario was slightly better than aggregate scenario. Specifically, for treatment IXE_Q4W, the range differences of 95% CI in the subgroup scenario (age: 2.262-2.923) and no subgroup scenario (2.3-3.038) were relatively visible. Thus, it showed that the impact of subgroup results on the calibration of relative treatment effects might not be so strong but still could be differentiated. Respecting the simulation of DoR, although we could still detect the difference between three scenarios, the differences between subgroup scenario and aggregate scenario were not much obvious as Figure xx shown.

#	Discussion (900-1000)
In this study, we proposed the extension of the ML-NMR accommodating the subgroup results in the existing ML-NMR framework and showed the whole process step by step. In the base scenario, the value of IPD was confirmed again. With the additional advantages of ML-NMR (xxx), this case study has affirmed that the input of subgroup level data could provide a more precise estimates of treatment effect and covariate-treatment interaction compared to the conventional aggregate level meta-analysis. Thus, apart from inherent advantages of ML-NMR method (xxx), the key advantage of this extension is to combine all available information considering the limited availability of clinical trial data. 

However, the limitations of this extension could not be neglected. With regard to the effect size of estimation, the difference between subgroup and aggregate scenario was not evident. Since there is only single subgroup factor was applied in this simulation, this simulation study could be extended to examine more subgroup factors. When multiple subgroup effects are considered, the subgroup results could be reported factorially (e.g. age and sex: younger and female; younger and male; older and female, older and male) then we need to consider whether subgroup results were correlated(xxx). 

Another concern of incorporating the subgroup result is oriented from the reporting bias. This may occur when the subgroup result is reported inconsistently without sufficient information of study or insufficient pre-specified outcomes were reported, which means when this kind of information was selected into the meta-analysis, the synthetic evidence was not reliable. Nonetheless, it has been demonstrated that the adoption of multivariate NMA could eliminate the influence of outcome reporting bias. (hwang2018)

Furthermore, the availability of subgroup results also halts the implementation of this method. Typically, subgroup analysis was conducted for multiple baseline characteristics no matter what pre-specified analysis or post-hoc analysis. Unlike post-hoc analysis what we did in this study, it could be more challenge to collect enough pre-specified subgroup results.

The limitations mentioned above lead to further investigation for this extened application. It could be possible to accommodate multiple subgroups by estimating correlations of subgroup effects given the correlations between multiple subgroup factors are assumed exchangeable. Furthermore, regarding the availability of subgroup results, we could also investigate to combine the aggregate-level baseline characteristics only in the ML-NMR framework assuming the correlations between baseline characteristics are exchangeable.

# Conclusions

To our knowledge, this is the first study that combine the subgroup results with IPD, and aggregate-level data in the network meta-analysis. We demonstrated this extended approach in a semi-tutorial style with the existing simulated data and R package. Also, we are able to show that the extra benefits of subgroup results in the ML-NMR, providing a more precise estimation of covariate-treatment interaction and population-adjusted relative treatment effects compared to the traditional meta-analysis. Researhcers doing meta-analysis may wish to consider doing so, at least in sensitivity analyses and exploratory analyses.

